# Generated by Django 6.0.8 on 2026-09-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification_education_sociallink_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Certification', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Informations de contact', 'verbose_name_plural': 'Informations de contact'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profil'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Competence', 'verbose_name_plural': 'Competences'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Reseau social', 'verbose_name_plural': 'Reseaux sociaux'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Statistique', 'verbose_name_plural': 'Statistiques'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Technologie', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Temoignage', 'verbose_name_plural': 'Temoignages'},
        ),
    ]
