# Generated by Django 6.0.8 on 2026-09-09 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, verbose_name='lien du certificat'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date_obtained',
            field=models.DateField(verbose_name="date d'obtention"),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(max_length=200, verbose_name='organisme'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='form_active',
            field=models.BooleanField(default=True, verbose_name='formulaire de contact actif'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=200, verbose_name='diplome'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, help_text='Laisser vide si en cours', null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200, verbose_name='etablissement'),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(verbose_name='date de debut'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=200, verbose_name='entreprise'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, help_text='Laisser vide si en cours', null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='date de debut'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='type',
            field=models.CharField(help_text='Ex: Stage professionnel, Freelance, Benevolat', max_length=100, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='available',
            field=models.BooleanField(default=True, verbose_name='disponible'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, upload_to='profile/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='nom complet'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='profile/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=200, verbose_name='poste'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis a jour le'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='categorie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Presentation du projet pour la fiche detaillee', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, default='', help_text="URL du site en ligne, laisser vide ou '#' si aucun", max_length=500, verbose_name='lien'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, help_text='Defis releves / resultats obtenus', verbose_name='resultats'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='Ex: Developpeur full-stack solo', max_length=200, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.technology', verbose_name='technologies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='niveau (%)'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(help_text='Ex: GitHub, LinkedIn, Twitter/X', max_length=50, verbose_name='plateforme'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='label',
            field=models.CharField(max_length=100, verbose_name='libelle'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='suffix',
            field=models.CharField(blank=True, help_text='Ex: %, +', max_length=20, verbose_name='suffixe'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value',
            field=models.IntegerField(verbose_name='valeur'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='logo',
            field=models.ImageField(upload_to='technologies/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_role',
            field=models.CharField(blank=True, help_text='Ex: CEO chez Startup Boost', max_length=200, verbose_name='fonction'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(verbose_name='temoignage'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, upload_to='testimonials/', verbose_name='photo'),
        ),
    ]
