# Generated by Django 6.0.8 on 2026-09-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_certification_credential_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='site_name',
            field=models.CharField(blank=True, help_text='Affiche dans la barre de navigation et le pied de page. Laisser vide pour utiliser le nom complet.', max_length=100, verbose_name='nom du site / marque'),
        ),
    ]
