# Generated by Django 6.0.8 on 2026-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_profile_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="Utilisee comme texture sur l'objet 3D de l'accueil (distincte de la photo de profil).", upload_to='profile/', verbose_name='image de la scene 3D'),
        ),
    ]
