# Generated by Django 6.0.8 on 2026-09-10 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_profile_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text="Affichee derriere les etoiles, en fond de l'accueil.", upload_to='profile/', verbose_name='image de fond de la scene 3D'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_background_opacity',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="opacite de l'image de fond (%)"),
        ),
    ]
